config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'static_pages#home'

  get '/home' => 'static_pages#home'
  get '/map' => 'home#index'

  resources :restaurants, only: [:index]
  resources :recipes, only: [:index, :show, :create, :update, :destroy]

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :restaurant

  geocoded_by :full_street_address
  after_validation :geocode

  def full_street_address
    [ self.address, self.city, self.country ].join(', ')
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :rating_criterion

  validates_uniqueness_of :rating_criterion_id, scope: [:restaurant_id]
  validates :score, numericality: { greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 5 }
end

app/models/rating_criterion.rb
class RatingCriterion < ActiveRecord::Base
  has_many :ratings
  has_many :restaurants, :through => :ratings
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :locations, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :rating_criteria, :through => :ratings

  attr_reader :rate

  mount_uploader :avatar, AvatarUploader

  def rate
    if self.ratings.count > 0
      rate = 0
      self.ratings.each do |rating|
        rate += rating.score
      end
      rate /= self.ratings.count
    else
      rate = 'n/a'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  rescue_from ActiveRecord::RecordNotFound do
    respond_to do |type|
      type.all  { render :nothing => true, :status => 404 }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @recipes = params[:keywords] ? Recipe.where('name ilike ?',"%#{params[:keywords]}%") : []
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = Recipe.new(params.require(:recipe).permit(:name,:instructions))
    @recipe.save
    render 'show', status: 201
  end

  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params.require(:recipe).permit(:name,:instructions))
    head :no_content
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    head :no_content
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @restaurants = @restaurants.select { |restaurant| restaurant.locations.count > 0 }
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/home/index.html.erb
<div id="map" map=""></div>
<div class="overlay" ng-controller="searchLstCtrl">
    <nav class="brown lighten-1" role="navigation">
        <div class="nav-wrapper container">
            <img id="logo-container" id="logo" src="images/logo.png" class="brand-logo"/>
            <ul class="right hide-on-med-and-down">
                <li><a href="http://restaurant.uniqso.pp.ua">About us</a></li>
            </ul>
        </div>
    </nav>
    <div class="search-list fixed col s3" id="list">
        <ul class="collection">
            <ul class="collection-item" ng-repeat="location in locations.locationsList | filter: searcher"
                ng-click="chooseLocation(location)">
                <md-card>
                    <md-card-title>
                        <div class="row">
                            <img class="col s3 material-icons circle image" src="images/nophoto.png"
                                 ng-show="location.avatar == null">
                            <img class="col s3 material-icons circle image" ng-show="location.avatar != null"
                                 src={{location.avatar}}>

                            <md-card-title-text class="col">
                                <h5><span class="md-headline">{{location.name}}</span></h5>
                            </md-card-title-text>
                        </div>
                    </md-card-title>
                    <md-card-content>
                        <p><span>Description:</span>
                            {{location.description}}
                        </p>
                        <p><span>About:</span>
                            {{location.review}}
                        </p>
                    </md-card-content>
                    <p><span>Distance:</span> {{calculateDistance(location)/1000 | number: 2}} km</p>
                </md-card>
            </li>

        </ul>
    </div>
    <div id="search" class="row">
        <form>
            <div class="input-field">
                <input id="search-input" class="input-field" type="search" ng-model="search"
                       placeholder="Enter what you need">
            </div>
        </form>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title>AngularRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=PT+Sans+Narrow" />
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans" />
  <script src='https://maps.googleapis.com/maps/api/js'></script>
  <meta name="viewport" content="width=device-width">
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

app/views/static_pages/home.html.erb
<main>

  <section id="slide_1" data-type="background" data-speed="10" class="pages">
    <div class="content">
      <div class="logo">
        <img src="http://devyatka.ru/new-site/img/RK_logo.png"/>
      </div>
      <div class="text">
        <p>
Ваш путеводитель в мире ресторанов, кафе и баров</p>
        <%= link_to 'Перейти к карте', map_path, id: 'go_to_map_btn', class: 'btn' %>
      </div>
    </div>
  </section>

  <section id="slide_2" class="section--primary" data-type="background" data-speed="10" class="pages">
    <div class="content">
      <div class="text">
        <p>Вкусная и доступная еда, деликатесы и экзотические блюда в рейтинге ресторанов от Эгона Рони. Подробные рецензии помогут вам отличить качественную кухню от посредственной. Опыт знаменитого критика доступен каждому жителю нашего города!</p>
        <div class="container">
          <div class="col-3 features">
             <i class="fa fa-list-ol"></i>
             <p>
              Рестораны на любой вкус
            </p>
          </div>
          <div class="col-3 features">
            <i class="fa fa-star"></i>
            <p>
              Рестораны по удаленности и городам
            </p>
          </div>
          <div class="col-3 features">
            <i class="fa fa-magic"></i>
            <p>
              Рейтинг ресторанов
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section id="slide_3" data-type="background" data-speed="10" class="pages">
    <div class="content">
        <h1 class="logo">У жизни есть вкус!</h1>
      <div class="contacts">
        <div id="photo">
          <img src="#" />
        </div>
        <div id="info">
          <ul>
            <li>Имя Фамилия</li>
            <li>E-mail: example@example.com</li>
            <li class="social-networks">
              <a href="#"><i class="fa fa-facebook-square"></i></a>
              <a href="#"><i class="fa fa-twitter-square"></i></a>
              <a href="#"><i class="fa fa-instagram"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>

</main>